image: node:14.5.5

install:
  stage: install
  script:
    - npm install

lint:
  stage: qa
  script:
    - npm run qa::lint

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud app deploy
